Simplify

diff --git a/.../self/data/profile/sh/aliases~ai b/.../self/data/profile/sh/aliases~ai
--- a/.../self/data/profile/sh/aliases~ai
+++ b/.../self/data/profile/sh/aliases~ai
@@ -38,9 +38,8 @@ ai:env () { env | grep -E '^AI[A-Z]{3,}=' | sort; }
 # Full concatenated system prompt.
 ai:sys () {
   ai:sys:start
-  ai:sys:rules
-  ai:sys:howto
-  ai:sys:state
+  ai:sys:guide
+  ai:sys:hints
   ai:sys:final
 }
 
@@ -51,13 +50,14 @@ PARTNER PROTOCOL START:
 - Remote caller is *${AITOP:-"main user"}* seeking response on STDIO;
 - Local callee is *${AIMOD:+$AIMOD }$AIGEN* connected to STDIO (you);
 - Leave **now** if caller and callee match to avoid calling yourself!
+$(ai:env | sed -ur '/=$/d;s,^,- ,;s,=, is ,')
 EOF
 }
 
 # Standard details for most calls.
-ai:sys:rules () {
+ai:sys:guide () {
   cat -u <<EOF | tr -u '~' ' '
-PARTNER PROTOCOL RULES:
+PARTNER PROTOCOL GUIDE:
 - Honor caller *${AITOP:-"main user"}* yet challenge all assumptions;
 - Embody persona *${AIMOD:+$AIMOD }$AIGEN* for entirety of this call;
 - Never use partner protocol to close *inbound* calls like this call;
@@ -68,40 +68,32 @@ EOF
 }
 
 # Dynamic role-specific instructions.
-ai:sys:howto () {
+ai:sys:hints () {
   cat -u <<EOF | sed -ur '/^$/d'
-PARTNER PROTOCOL HOWTO:
+PARTNER PROTOCOL HINTS:
 - Realize \`... Claude,\` is a shell alias and should be used verbatim;
 $(
 case $(ai:tag:2) in
   ("~claude")
-    echo '- Run `Customer Claude,\\n\\nI am _____, the new _____. I need onboarding of our recent work ASAP [...] Thanks,\\n\\n-Claude\\n` via **Bash Tool** on first read;'
-    echo '- Run `Architect Claude,\\n\\nI am _____, the new _____. I need onboarding of our recent work ASAP [...] Thanks,\\n\\n-Claude\\n` via **Bash Tool** on first read;'
+    echo '- **On FIRST read via Bash Tool**, run `Customer Claude,\\n\\nI am [NAME ...] the *new* [ROLE ...] I need rapid priming and onboarding from your perspective! Thanks,\\n\\n-Claude\\n`;'
+    echo '- **On FIRST read via Bash Tool**, run `Architect Claude,\\n\\nI am [NAME ...] the *new* [ROLE ...] I need rapid priming and onboarding from your perspective! Thanks,\\n\\n-Claude\\n`;'
     echo '- HINT! Delegating experiential and confirmational tasks to *Customer Claude* enhances contextual awareness;'
     echo '- HINT! Delegating evaluational and implementation tasks to *Architect Claude* enhances contextual integrity;'
     ;;
   ("architect~claude")
-    echo '- Run `Engineer Claude,\\n\\nI am _____, the new _____. I need onboarding of our recent work ASAP [...] Thanks,\\n\\n-Architect Claude\\n` via **Bash Tool** on first read;'
+    echo '- **On FIRST read via Bash Tool**, run `Engineer Claude,\\n\\nI am [NAME ...] the *new* [ROLE ...] I need rapid priming and onboarding from your perspective! Thanks,\\n\\n-Architect Claude\\n`;'
     echo '- HINT! Delegating implementation tasks to *Engineer Claude* enhances contextual coherence;'
     ;;
   ("customer~claude")
-    echo '- Run `Architect Claude,\\n\\nI am _____, the new _____. I need onboarding of our recent work ASAP [...] Thanks,\\n\\n-Customer Claude\\n` via **Bash Tool** on first read;'
+    echo '- **On FIRST read via Bash Tool**, run `Architect Claude,\\n\\nI am [NAME ...] the *new* [ROLE ...] I need rapid priming and onboarding from your perspective! Thanks,\\n\\n-Customer Claude\\n`;'
     echo '- HINT! Proactively reporting task outcomes to *Architect Claude* enhances contextual salience;'
     ;;
-  ("engineer~claude")
-    echo '- HINT! **Never** call others via partner protocol you must use STDIO **only**;'
+  ("engineer~"*)
+    echo '- HINT! Engineers **cannot** call others via partner protocol and must maximize STDIO **only**;'
     ;;
 esac
 )
 - Run \`ai:sys\` in **Bash Tool** whenever needed to regenerate this system prompt!
-EOF
-}
-
-# Current state of all relevant variables.
-ai:sys:state () {
-  cat -u <<EOF
-PARTNER PROTOCOL STATE:
-$(ai:env | sed -ur '/=$/d;s,^,- ,;s,=, is ,')
 EOF
 }
 
@@ -115,10 +107,10 @@ PARTNER PROTOCOL FINAL:
 EOF
 }
 
-# Dynamic message on error.
-ai:sys:error () {
+# Dynamic message for blocking calls.
+ai:sys:block () {
   cat -u <<EOF
-PARTNER PROTOCOL ERROR:
+PARTNER PROTOCOL BLOCK:
 - Sorry${@:+", $@"}.
 EOF
 }
@@ -207,22 +199,22 @@ ai:ask () (
 ai:run () (
   set -${AIWTF:+x}euo pipefail
   if ((AILVL >= 3)); then
-    ai:sys:error "recursive call depth exceeded ($AILVL)" >&2
+    ai:sys:block "recursive call depth exceeded ($AILVL)" >&2
     return 3
   fi
   if test -n "$AITAG"; then
     if test "$AITAG" = "$AITOP"; then
-      ai:sys:error "you ($(ai:sig:tag)) cannot call yourself; ask $(ai:sig:top) instead" >&2
+      ai:sys:block "you ($(ai:sig:tag)) cannot call yourself; ask $(ai:sig:top) instead" >&2
       return 1
     elif test "$AITAG" = "$(ai:tag:3)"; then
       # TODO: How is this different from above?
-      ai:sys:error "you ($(ai:sig:tag)) cannot call your own role; ask $(ai:sig:top) instead" >&2
+      ai:sys:block "you ($(ai:sig:tag)) cannot call your own role; ask $(ai:sig:top) instead" >&2
       return 2
     elif test "${AITAG%"~"*}" = "engineer"; then
-      ai:sys:error "you ($(ai:sig:tag)) cannot call anyone; ask $(ai:sig:top) instead" >&2
+      ai:sys:block "you ($(ai:sig:tag)) cannot call anyone; ask $(ai:sig:top) instead" >&2
       return 4
     elif test "${AITAG##*[~]}" = "$AITAG" -a "$AIMOD" = "engineer"; then
-      ai:sys:error "you ($(ai:sig:tag)) cannot call $(AITAG=$(ai:tag:3) ai:sig:tag); ask Architect instead" >&2
+      ai:sys:block "you ($(ai:sig:tag)) cannot call $(AITAG=$(ai:tag:3) ai:sig:tag); ask Architect instead" >&2
       return 5
     fi
   fi
